[package]
name = "bouncycastle-factory"
version.workspace = true
edition.workspace = true

[dependencies]
bouncycastle-ascon.workspace = true
bouncycastle-core.workspace = true
bouncycastle-sha2.workspace = true
bouncycastle-sha3.workspace = true
bouncycastle-sm3.workspace = true
bouncycastle-rng.workspace = true

[dev-dependencies]
bouncycastle-core-test-framework.workspace = true
bouncycastle-utils.workspace = true
bouncycastle-hex.workspace = true
