[package]
name = "bouncycastle-sha2"
version.workspace = true
edition.workspace = true

[dependencies]
bouncycastle-core.workspace = true
bouncycastle-hkdf.workspace = true
bouncycastle-hmac.workspace = true
bouncycastle-utils.workspace = true

[dev-dependencies]
criterion.workspace = true
bouncycastle-core-test-framework.workspace = true
bouncycastle-rng.workspace = true
bouncycastle-hex.workspace = true

[[bench]]
name = "sha2_benches"
harness = false

[[bench]]
name = "hkdf_sha2_benches"
harness = false

[[bench]]
name = "hmac_sha2_benches"
harness = false
